
INSERT INTO FORFAIT (NOM, UNITE)
VALUES ('APPEL', 'AR'), ('SMS', 'SMS'), ('INTERNET', 'Mo'), ('FACEBOOK', 'Mo');

INSERT INTO OFFRE (IDOFFRE, NOMOFFRE, DESCRIPTION)
VALUES ('DEFAUT', 'DEFAUT', 'DEFAUT');

INSERT INTO OFFREFORFAIT (IDOFFRE, IDFORFAIT) 
VALUES ('DEFAUT', 1), ('DEFAUT', 2), ('DEFAUT', 3);

INSERT INTO PRIXOFFRE (IDOFFRE, IDFORFAIT, PRIX, VALIDITE, COUT) 
VALUES 
        ('DEFAUT', 1, 0, NULL, '{1.0, 3.0, 6.0}'),
        ('DEFAUT', 2, 0, NULL, '{100.0, 120.0, 200.0}'),
        ('DEFAUT', 3, 0, NULL, '{0.5}');


