
INSERT INTO FORFAIT (NOM, UNITE)
VALUES ('TOUS', 'AR'), ('APPEL', 'AR'), ('SMS', 'SMS'), ('INTERNET', 'Mo'), ('FACEBOOK', 'Mo');

INSERT INTO OFFRE (IDOFFRE, NOMOFFRE, DESCRIPTION)
VALUES ('DEFAUT', 'DEFAUT', 'DEFAUT') , ('MOBILEMONEY', 'MOBILEMONEY', 'MOBILEMONEY');

INSERT INTO OFFREFORFAIT (IDOFFRE, IDFORFAIT) 
VALUES ('DEFAUT', 1);

INSERT INTO PRIXOFFRE (IDOFFRE, IDFORFAIT, PRIX, VALIDITE, COUT) 
VALUES 
        ('DEFAUT', 1, 0, NULL, '{1.0, 3.0, 6.0}'),
        ('DEFAUT', 2, 0, NULL, '{100.0, 120.0, 200.0}'),
        ('DEFAUT', 3, 0, NULL, '{0.5}');


