
INSERT INTO FORFAIT (IDFORFAIT, NOMFORFAIT, DATAUNITE, CONSOUNITE)
VALUES ('TOUS', 'TOUS', 'AR', '');

INSERT INTO FORFAIT (NOMFORFAIT, DATAUNITE, CONSOUNITE)
VALUES ('APPEL', 'AR', 's'), 
        ('SMS', 'SMS', 'SMS'), 
        ('INTERNET', 'Mo', 'Mo'),
        ('FACEBOOK', 'Mo', 'Mo');

INSERT INTO SOUSFORFAIT (IDFORFAIT, NOMSOUSFORFAIT, COUTCREDIT, COUTOFFRE)
VALUES 
        ('FRF1', 'APPEL MEME OPERATEUR', 1.0, 1.0), 
        ('FRF1', 'APPEL AUTRE OPERATEUR', 2.0, 2.0), 
        ('FRF1', 'APPEL INTERNATIONAL', 6.0, 6.0), 
        ('FRF2', 'MESSAGE MEME OPERATEUR', 100.0, 1.0), 
        ('FRF2', 'MESSAGE AUTRE OPERATEUR', 120.0, 1.0),
        ('FRF3', 'INTERNET', 0.5, 1.0),
        ('FRF4', 'FACEBOOK', 0.5, 1.0); 

INSERT INTO OFFRE (IDOFFRE, NOMOFFRE)
VALUES ('DEFAUT', 'DEFAUT');

INSERT INTO SOUSOFFRE (IDSOUSOFFRE, IDOFFRE, PRIX, VALIDITE)
VALUES ('DEFAUT', 'DEFAUT', 0, 0);


SELECT * FROM SOUSOFFRE NATURAL JOIN VOLUMESOUSOFFRE WHERE IDSOUSOFFRE='%s';